apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: northwaysignal-website
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "ca-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - northway.eldertree.local
      secretName: northway-tls
  rules:
    - host: northway.eldertree.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: northwaysignal-website
                port:
                  number: 80



