apiVersion: v1
kind: Service
metadata:
  name: northwaysignal-website
  namespace: default
spec:
  selector:
    app: northwaysignal-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
  type: ClusterIP

